# Generated by Django 2.1.7 on 2019-03-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre(s)', max_length=200)),
                ('a_paterno', models.CharField(help_text='Apellido Paterno', max_length=200)),
                ('a_materno', models.CharField(help_text='Apellido Materno', max_length=200)),
                ('f_nacimiento', models.DateTimeField(blank=True, help_text='Fecha de nacimiento', null=True)),
            ],
        ),
    ]
