# Generated by Django 2.1.7 on 2019-03-13 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='maestro',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Materia'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Maestro'),
        ),
    ]
